### ISSUE TITLE
hand in statt hand over

### ISSUE THREAD

**Issue by anna-gostler** [woeps/hci-gsi-calc#1]
Hi, cooles Projekt.
Aber es heißt hand in (Einreichen von Hausaufgaben) nicht hand over (ausliefern (um vor Gericht zu stehen)) ;)

**Comment by lorenzleutgeb** [comment]
Striked me too. Fixed in #2

**Comment by woeps** [comment]
Danke für deine Mithilfe!
Pull request merged.
