### ISSUE TITLE
Hosting on GitHub

### ISSUE THREAD

**Issue by lorenzleutgeb** [woeps/hci-gsi-calc#3]
I'd suggest you rename `master` to `gh-pages`, that way you would get hosting on GitHub for free, and you would not have to copy files to `web.student.tuwien.ac.at` on every new revision. This can be done in the repository settings of GitHub after pushing `master` as `gh-pages` like so:

``` bash
$ git checkout master
$ git branch gh-pages
$ git push --set-upstream origin gh-pages
```

You'd have to fix your relative includes, though. For example repoint them to some could provider (I would not be concerned about the security implications in this case).

**Comment by woeps** [comment]
Thanks for the tipp!! - I hadn't used gh-pages yet.

At least for the moment I'd like to keep separate branches for master (kinda "current dev") and gh-pages (kinda "dist" with compiled stylesheet).

Seems like a clean solution:
- master will contain all necessarities for the project to develope and compile
- gh-pages will only contain files needed to be rendered in the browser

I pushed the new branch to github: c791b4a

btw: I also _do_ speak german. ;)

**Comment by lorenzleutgeb** [comment]
> Seems like a clean solution

Only if `gh-pages` does not branch away from `master` (`git checkout --orphan gh-pages`) as suggested by [the corresponding article on GitHub](https://help.github.com/articles/creating-project-pages-manually/).

Right now you are _doing it wrong_™. You'll get loads of unnecessary changes. Prepare master for distribution and force push to `gh-pages` on every "release".

**Comment by woeps** [comment]
Thanks for your tip! - I (tried to) fix this. fce57480c7

**Comment by lorenzleutgeb** [comment]
Yup, looks better. But still, you don't need to track changes on `gh-pages` as they should all be reflected in `master` are only redundant on `gh-pages`.

**Comment by woeps** [comment]
Well, after running in some small troubles during pushing updates to the old gh-pages branch, finally I saw the true benefits of your first suggestion and set it up like you said: just using the gh-pages branch
Looks like it's all functioning again and I learned some new things about github. ;)
Thanks!

**Comment by lorenzleutgeb** [comment]
:sparkles: Great to hear that! :+1:
